version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      timeout: 3s

  api:
    build:
      context: ..  # Chỉ định thư mục cha (gốc của project)
      dockerfile: DOCA.API/Dockerfile  # Chỉ định Dockerfile trong DOCA.API
    container_name: dotnet-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_CONNECTION_STRING=redis-container:6379
    networks:
      - mynetwork
    volumes:
      - ..:/app  # Đồng bộ toàn bộ source code từ máy host vào container

networks:
  mynetwork:

volumes:
  redis_data:
